Homework2
Eugene-000/ibs pull request #2
Opened 2022-12-30 21:11 UTC by Eugene-000

ДЗ2. Получение данных и поиск по странице списка

2023-01-09 08:11 UTC, st-slav reviewed
файлы catalog.js и detaled.js не совсем про API, давай вынесем их из этой папки просто в папку scripts

2023-01-09 08:11 UTC, st-slav commented on hometask2/Scripts/API/catalog.js
> +                        <img src="${picturePath}" alt="${item.picture.alt}" class="item__img">
здесь можно просто устанавливать путь до изображения, браузер сам всё подтянет

2023-01-09 08:11 UTC, st-slav commented on hometask2/Scripts/API/api.js
> +            content = await response.blob();
это пока не требуется

2023-01-09 08:11 UTC, st-slav commented on hometask2/Scripts/API/catalog.js
> +    const cards = await fetchItems('http://localhost:3006/item', 'json');
http://localhost:3006

надо вынести в константы и переиспользовать, файл можно назвать constants.js

2023-01-09 08:11 UTC, st-slav commented on hometask2/Scripts/API/catalog.js
> +    const fetchCards = await Promise.resolve(cards);
должно работать без этого кода

2023-01-09 08:11 UTC, st-slav commented on hometask2/Scripts/API/catalog.js
> +                <a href="detailed.html?${item.id}" class="item__link">
давай давай будем использовать название переменной, т. е. ?id=3421, а потом извлекать при помощи new URLSearchParams(window.location.search);

2023-01-09 08:11 UTC, st-slav commented on hometask2/Scripts/API/api.js
> +    let id = param.substring(1);
new URLSearchParams(window.location.search) давай будем извлекать именованные параметры при помощи

2023-01-09 08:11 UTC, st-slav commented on hometask2/Scripts/API/api.js
> +function getParam(key) {
давай создадим файл utils.js и внесем эту функцию туда

2023-01-09 08:13 UTC, st-slav requested changes
комментарии к hometask2/Scripts/API/catalog.js так же относятся к hometask2/Scripts/API/detailed.js

2023-01-10 22:52 UTC, Eugene-000 commented
Поправлено

2023-01-11 10:59 UTC, st-slav approved these changes

2023-01-11 10:59 UTC, st-slav commented on hometask2/Scripts/detailed.js
> +        favourite = (item.like) ? 'active' : 'non-active';
можно сразу при объявлении присваивать значение, типа так:

const favourite = (item.like) ? 'active' : 'non-active';
const resultContainer = `......`

2023-01-11 10:59 UTC, merged