ДЗ3. Сборка проекта через webpack и реализация функции debounce.
Eugene-000/ibs pull request #3
Opened 2023-01-16 22:17 UTC by Eugene-000

2023-01-17 08:19 UTC, st-slav requested changes
давай файлы из папки project вынесем в корневую папку проекта

2023-01-17 08:19 UTC, st-slav commented on project/package.json
> +      "lodash": "^4.17.21",
эта либа не используется, возможно стоит удалить её

2023-01-17 08:19 UTC, st-slav commented on project/package.json
> +      "normalize.css": "^8.0.1"
эта либа не используется, возможно стоит удалить её

2023-01-17 08:19 UTC, st-slav commented on project/package.json
> +      "@babel/polyfill": "^7.12.1",
возможно @babel/polyfill стоит унести в devDependencies

2023-01-17 08:19 UTC, st-slav commented on project/src/catalog.js
> +    elSearch.addEventListener('keyup', debounceSearch(() => searchFilter(elSearch), 2000));
здесь не совсем правильно, колбек который передаётся вторым аргументом в addEventListener должен принимать event аргументом и получать из него значение, т. е. нужно доработать функцию которую возвращает debounceSearch таким образом, чтоб она получала значение

2023-01-17 17:20 UTC, Eugene-000 commented
Поправлено

2023-01-19 06:14 UTC, st-slav requested changes

2023-01-19 06:14 UTC, st-slav commented on src/search.js
> +          callback(e.target.value);
таким образом мы жёстко привязываем функцию debounce к event, давай value будем извлекать за пределами функции debounce, тогда мф функцию debounce сможем использовать ещё в других местах если потребуется

2023-01-19 19:39 UTC, Eugene-000 commented
Поправлено

2023-01-21 06:45 UTC, st-slav approved these changes

2023-01-21 06:45 UTC, st-slav commented on src/catalog.js
> +import { searchFilter } from './search';
здесь можно было так:
import { searchFilter, debounceSearch } from './search';

2023-01-21 06:45 UTC, st-slav commented on src/search.js
> +    return function(argument) {
здесь чтоб не ограничивать функцию одним аргументом можно сделать так
    return function(...argument) {
        clearTimeout(timeout);
        timeout = setTimeout(callback, delay, ...argument);
    }

2023-01-21 06:45 UTC, merged