ДЗ5. Перенос проекта на React-функциональные компоненты
Eugene-000/ibs pull request #5
Opened 2023-01-29 00:53 UTC by Eugene-000

2023-01-30 12:05 UTC, st-slav requested changes

2023-01-30 12:05 UTC, st-slav commented on src/API/itemApi.js
> +export class ItemApi {
давай объединим itemApi.js и ItemsApi.js т. к. они относятся к одной сущности

2023-01-30 12:05 UTC, st-slav commented on src/components/Header/Header.jsx
> +                        <img src={imgCart} alt="Cart" className="imgCart"/>
не нашёл такого класса, если он всё же где-то есть давай тогда импортировать его как module.scss

2023-01-30 12:05 UTC, st-slav commented on src/components/Header/Header.jsx
> +                        <img src={imgProfile} alt="Profile" className="imgProfile"/>
не нашёл такого класса, если он всё же где-то есть давай тогда импортировать его как module.scss

2023-01-30 12:05 UTC, st-slav commented on src/components/UI/Search/Search.jsx
> +            <svg className={styles.svg} width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
давай svg вынесем в assets, в отдельный svg файл

2023-01-30 12:05 UTC, st-slav commented on src/components/ListItems/Item/Item.jsx
> +        {item.like
можно так:
`<button type="button" className={[styles.favouriteBtn, item.like ? styles.active : styles.nonActive].join(' ')}></button>`

2023-01-30 12:05 UTC, st-slav commented on src/pages/Catalog/Catalog.jsx
> +    const debouncedHandleSearch = useMemo(() => {
1. здесь useCallback больше подойдёт:
`
const debouncedHandleSearch = useCallback(debounceSearch(setSearchQuery, 2000))
`
обрати внимание что вместо handleSearch использовал setSearchQuery, т. к. либо handleSearch надо было добавить в зависимости useMemo, но т. к. handleSearch бы обрабатывался при каждом рендере, надо было либо обернуть его в useCallback, но решил использовать его напрямую

2023-01-30 12:05 UTC, st-slav commented on src/components/App/App.jsx
> +          <Route path='/' element={<Catalog />} />
давай path вынесем в константы и будем использовать по всему приложению, т. к. если вдруг будет переименование роута (что бывает периодически) придётся искать по всему проекту его использование

2023-01-30 12:05 UTC, st-slav commented on src/components/ItemInfo/ItemInfo.jsx
> +                            {item.like
можно так:
`<button type="button" className={[styles.favouriteBtn, item.like ? styles.active : styles.nonActive].join(' ')}></button>`

можно вынести в отдельный компонент и использовать на двух страницах

2023-01-31 23:44 UTC, Eugene-000 commented
Поправил

2023-02-02 14:20 UTC, st-slav requested changes
давай сделаем примерно такую структуру

```
src
  ├── components                        // здесь будут общие компоненты для всех страниц
  |
  ├── pages                             // здесь будут страницы
  |     ├── detailed
  |     |    ├── components             // здесь будут компоненты которые только на этой странице
  |     |    | 
  |     |    ├── Detailed.js            // здесь собираем страницу из компонентов и получаем данные
  |     |    ├── Detailed.module.scss
  |     |    ├── index.js               // здесь экспортируем компонент наружу
  |     ├── index.js
  | ........
  |
  ├── api
  |     ├── items.js
  |     ├── index.js
  |
  ├── constants                       // здесь будут константы и файлы с константами общие для всего приложения
  |
  ├── lib                             // здесь будут храниться утилитарные файлы
  |    ├── debounce.js
  | ......
```

2023-02-02 20:40 UTC, Eugene-000 commented
Поправил

2023-02-03 18:25 UTC, Eugene-000 commented
Всё поправил

2023-02-06 08:49 UTC, st-slav approved these changes

2023-02-06 08:49 UTC, st-slav commented on src/pages/Catalog/Catalog.jsx
> +    const debouncedHandleSearch = useCallback(debounceSearch(setSearchQuery, 2000))
необходимо указать пустой массив зависимостей

2023-02-06 08:49 UTC, st-slav commented on src/pages/Catalog/Catalog.jsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
не совсем верно использовать эффект без зависимостей, давай эту логику инкапсулируем в хук useFetching, см. коммент в useFetching

2023-02-06 08:49 UTC, st-slav commented on src/hooks/useFetching.js
> +export const useFetching = (callback) => {
давай перепишем этот хук немного по другому:

```
export const useFetching = (callback, deps) => { // deps - это массив зависимостей
    const [data, setData] = useState();
    const [isLoading, setIsLoading] = useState(false);
    const [error, setError] = useState('');

  useEffect(() => {
    const fetching = async () => {
        try {
            setIsLoading(true);
            await callback();
        } catch (e) {
            setError(e.message);
        } finally {
            setIsLoading(false);
        }
    }

   fetching().then(data => setData(data))

  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, deps)

    return [data, isLoading, error];
}
```

пример использования на странице detailed:
```
    const [item, isLoading, error] = useFetching(() => {
        return ItemsApi.getItem(id);
    }, [id]); // если мы перейдём на другую страницу с этой же страницы, т. е. сменится id, тогда произойдёт перезапрос данных
```

пример использования на странице catalog:
```
    const [items, isLoading, error] = useFetching(() => {
        return ItemsApi.getItems();
    }, [])
```

2023-02-06 08:49 UTC, st-slav commented on src/components/Header/Header.jsx
> +                    <a href="/" className={styles.icon}>
здесь надо использовать константу, я так понимаю что эта ссылка ведёт на главную страницу, нужно использовать PATH_INDEX

2023-02-06 08:49 UTC, st-slav commented on src/components/Header/Header.jsx
> +                    <a href="/" className={[styles.icon, styles.iconProfile].join(' ')}>
здесь надо использовать константу, я так понимаю что эта ссылка ведёт на главную страницу, нужно использовать PATH_INDEX

2023-02-06 08:49 UTC, st-slav commented on src/App.jsx
> +import { PATH_DETAILED } from "./constants/routes";
можно сделать через один импорт:
import { PATH_INDEX, PATH_DETAILED } from "./constants/routes";

2023-02-06 08:49 UTC, st-slav commented on src/pages/Catalog/components/ListItems/components/Item/Item.jsx
> +      <Link className={styles.linkItem} to={`/${item.id}`}>
создание ссылки на страницу detailed, лучше сделать с использованием контсанты роута, т. е. PATH_DETAILED, т. к. если в дальнейшем мы изменим константу этого роута, нам не нужно было искать по всему приложению ссылки на неё, можно написать функцию, типа:
`
const createDetailedPath = (id) => PATH_DETAILED.replace(':id', id)
`

2023-02-06 08:56 UTC, st-slav commented on src/pages/Catalog/Catalog.jsx
> +    const debouncedHandleSearch = useCallback(debounceSearch(setSearchQuery, 2000))
т. е. будет вот так:
`const debouncedHandleSearch = useCallback(debounceSearch(setSearchQuery, 2000), [])`

2023-02-07 20:59 UTC, merged