ДЗ6. Добавление Redux, typescript, material-ui
Eugene-000/ibs pull request #6
Opened 2023-02-13 01:24 UTC by Eugene-000

2023-02-15 11:33 UTC, st-slav requested changes

2023-02-15 11:33 UTC, st-slav commented on src/store/modal/actions.ts
> +export const modal__setVisible = (text: string): ModalAction => ({
давай уберём эти префиксы - "modal__" по всему приложению, лучше делать отдельные хуки для определённого модуля

2023-02-15 11:33 UTC, st-slav commented on src/store/modal/types.ts
> +export interface modalState {
типы и интерфейсы лучше с большой буквы ModalState

2023-02-15 11:33 UTC, st-slav commented on src/store/modal/types.ts
> +interface SetInvisibleModalAction {
тут можно не писать тип для каждого экшена, можно использовать утилиту тайп скрипта ReturnType, например:
`export type ModalAction = ReturnType<typeof setVisible> | ReturnType<typeof setInvisible>`

вроде как должно сработать

2023-02-15 11:33 UTC, st-slav commented on src/store/items/reducer.ts
> +// export const itemsReducer = (
комментарии надо удалить

2023-02-15 11:33 UTC, st-slav commented on package.json
> +    "@types/jest": "^27.5.2",
это и всё что связано с типами надо в devDependencies

2023-02-15 11:33 UTC, st-slav commented on src/components/Modal/Modal.tsx
> +                    sx={{
sx лучше не использовать, лучше создать класс или через styled, надо что-то одно в проекте стараться использовать

2023-02-15 11:33 UTC, st-slav commented on src/pages/Catalog/components/ListItems/ListItems.tsx
> +      modal__setVisible(error);
вот эту логику моно унести в перехватчик axios (interceptors) и устанавливать там типа:
STORE.dispatch(setVisible(error.message))

2023-02-15 11:33 UTC, st-slav commented on src/models/items.ts
> +export interface IItems {
IItem

2023-02-18 00:09 UTC, Eugene-000 commented
Поправил

2023-02-21 09:06 UTC, st-slav approved these changes

2023-02-22 21:26 UTC, merged